### ISSUE TITLE
Make tracking optional and disabled by default

### ISSUE THREAD

**Issue by frgomes** [expo/xde#150]
It was observed that, under undetermined circumstances, [cdn.segment.com](http://cdn.segment.com) cannot be contacted.
For more details, please have a look at #149 

XDE tries to download ``analytics.min.js`` from [cdn.segment.com](http://cdn.segment.com), which cause errors in case [cdn.segment.com](http://cdn.segment.com) is down or cannot be contacted for whatever reason. Activities are tracked along the way, which potentially could cause troubles if [cdn.segment.com](http://cdn.segment.com) suddenly becomes unavailable. However, this possibility was not tested.

There's also an element of ethics here: tracking software may not be welcomed to a number of users. Not only that: tracking websites maybe purposely blocked by browser plugins, by routers or by ISPs, exactly because "tracking" is a controversial subject.

So, I would say that the desired behavior would be:

  - [ ] Ask for permission to track activities;
  - [ ] If the initial download of ``analytics.min.js`` fails, turn tracking activities down necessarily;
  - [ ] Test if tracking is enabled before trying to contact [cdn.segment.com](http://cdn.segment.com);
  - [ ] Protect the code so that attempts to track activities can be simply ignored in case of failure.

**Comment by frgomes** [comment]
I've create a "dirty fix" which "works for me" at
https://github.com/frgomes/xde/tree/unsegmented

It's a quick fix, which allows me go ahead. It's far from doing the right thing.

**Comment by brentvatne** [comment]
Hey @frgomes! Thanks for writing this up! Could you possibly repost this on  http://github.com/expo/expo/issues or move the discussion to a pull request on here? We try to consolidate all of our issues onto one repo in order to make it easier to manage.
